SELECT id,
       worker_reference,
       registration_id,
       worker_name,
       employer_id,
       toli_id,
       toli,
       aadhar,
       pan,
       bank_account,
       payment_amount,
       request_reference_number,
       receipt_number,
       status,
       file_id,
       uploaded_file_ref,
       created_at
FROM worker_payments
